/**
 * JSON Schema for a component's `metadata.yml` — the agent-facing catalog record.
 * Validated by ajv in `validate.js` / the catalog builder.
 *
 * `component.def.yml` owns prop/slot TYPES; this file owns prop/slot PROSE and
 * everything an agent needs to decide whether a component fits a task.
 */

export const THEMES = ["simple", "futuristic", "classic", "smooth"];
export const BREAKPOINTS = ["mobile", "tablet", "small", "desktop"];

/** @type {Record<string, any>} */
export const metadataSchema = {
  type: "object",
  additionalProperties: false,
  required: ["short_description", "lifecycle", "categorization"],
  properties: {
    short_description: { type: "string", minLength: 1 },
    long_visual_description: { type: "string" },

    use_cases: {
      type: "array",
      items: { type: "string", minLength: 1 },
      minItems: 5,
      maxItems: 15,
    },

    // theme -> breakpoint -> image path (generated by the screenshot pipeline).
    screenshots: {
      type: "object",
      additionalProperties: {
        type: "object",
        additionalProperties: { type: "string" },
      },
    },

    recommended_for: { type: "array", items: { type: "string" } },
    avoid_for: { type: "array", items: { type: "string" } },
    markets: { type: "array", items: { type: "string" } },
    example_usage: { type: "string" },

    // prose keyed by prop/slot name (types come from component.def.yml).
    props: { type: "object", additionalProperties: { type: "string" } },
    slots: { type: "object", additionalProperties: { type: "string" } },

    example_prompts: { type: "array", items: { type: "string" } },

    lifecycle: { type: "string", enum: ["experimental", "stable", "deprecated"] },
    content_model: { type: "string" },

    theming: {
      type: "object",
      additionalProperties: false,
      properties: {
        tokens_used: { type: "array", items: { type: "string" } },
      },
    },

    editorial_guidance: { type: "string" },

    categorization: {
      type: "object",
      additionalProperties: false,
      required: ["category", "atomic_type", "maturity"],
      properties: {
        category: { type: "string", minLength: 1 },
        subcategory: { type: "string" },
        atomic_type: { type: "string", enum: ["atom", "molecule", "organism", "full"] },
        usage_type: { type: "array", items: { type: "string" } },
        maturity: {
          type: "string",
          enum: ["ai-generated", "human-approved", "production-ready"],
        },
        wcag: {
          type: "object",
          additionalProperties: false,
          properties: {
            level: { type: "string", enum: ["A", "AA", "AAA"] },
            notes: { type: "string" },
          },
        },
        keyboard_support: { type: "string" },
        seo_score: { type: "integer", minimum: 0, maximum: 100 },
        text_direction: { type: "string", enum: ["ltr", "rtl", "both"] },
      },
    },
  },
};
